default_stages:
- pre-commit
exclude: .git|README.md|uv.lock|.csv|.ipynb
fail_fast: true
repos:
# Pre-commit hooks
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-merge-conflict
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
        files: \.(json)$
    -   id: check-toml
        files: \.(toml)$
    -   id: check-yaml
        files: \.(yaml)$
        args:
        - --unsafe  # allow !function tag
# Ruff
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.7
    hooks:
      - id: ruff
        name: ruff linter
        args: ["--diff"]
        types:
        - python
      - id: ruff-format
        name: ruff formatter
        args: ["--check", "--diff"]
        types: [python]
